branches:
  only:
    - master
sudo: false
language: node_js
addons:
  apt:
    packages:
    - calibre
    - calibre-bin
install:
  - npm install gitbook-cli -g
  - npm install svgexport -g
  - pip install --user beautifulsoup4
  - pip install --user ghp-import
node_js: '10.2'
# Using xvfb to Run Tests That Require a GUI
# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - make
  - make pdf
  - make test
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && make publish-travis || true'
env:
  global:
    secure: "A4LX7iDTTSEiRaWFuT7rLhCTG2Za/AQ/i43oG+3KPz1iOw7fBDfrUTJjZwHll7LJJx8mEKmqr5MzIu4qLatJO7kHLA1cb+OeNJAeLi+mQf6AsGlFxtJX/h/cFgxFJbjjzTAJDVy1TlID0dHAzk6Uu9Uo+ciatERJFtXH1GVc4UcjQpuVxEoVEA1sWP2uIpyv6sUjPoQcFLNp5zQT776x04WszFpu8mBVmDaCzSMOhWFC9DCRBIhkGGSdIvoE2GAoJWpHUpNDXZsugsQ/d0Dtii5oTIeZJnMTZA6K3EvYhBOp+bslj9a/+qheqkxjef2wBusDy/N8XWe/1iL2h9uM1sZIYAQC4lAgb9/sm2cVUVhg2zC3oo187Zcm/SaNMQBVuHS7GUmQUX8NXxcRvr1jqK72cpg6zYAdydl0yKscCY9AwmIwxjhc8FJ+H8q82GQyPuNn13KiCQkXv173fB9pRvQqUSlAR9YO0Y222Y+aSJokOMXyTKUSiOTYc1F0FX/wK/wm/LfWvRmjNkOINj7gZMFMJXCj9zpvp7sUh1Hz6eTp6UiOcnSHA3puKOWuuREF/CN5ETNCMtT8i/Q50TRC5HXA/pWc9u2SxRCViq277UuXv6c96wGKAnw5Cm/Mshcdfq03rq0wWamFeKxwewopFMX9k7af66Liu3fh0IzfmoQ="
