name: example-environment
channels:
  - conda-forge
dependencies:
  - hep_ml
  - hepunits
  - ipython
  - matplotlib
  - mplhep
  - nb_conda
  - nb_conda_kernels
  - numpy
  - pandas
  - particle
  - pandoc
  - pip
  - scikit-learn
  - scipy
  - tensorflow
  - uproot
  - uproot4 >0.1.2
  - wget
  - xgboost
  - pip:
    - git+https://github.com/hsf-training/python-lesson.git@0.0.2
    - zfit
    - hepstats
    - formulate
