name: example-environment
channels:
  - conda-forge
dependencies:
  - ipython
  - matplotlib
  - uproot
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - tensorflow
  - xgboost
  - hep_ml
  - wget
  - pip
  - pip:
    - git+https://github.com/hsf-training/python-lesson.git@0.0.2
